

import { Book, Review } from '@/types';


const reviewerNames = [
  'Alice M.', 'Bob T.', 'Clara D.', 'Daniel R.', 'Eva S.',
  'Frank L.', 'Grace K.', 'Henry J.', 'Irene P.', 'James W.',
  'Karen B.', 'Leo H.', 'Maya N.', 'Nathan Q.', 'Olivia C.',
];

const reviewComments = [
  'Absolutely loved this book! Could not put it down.',
  'A masterpiece of storytelling. Highly recommended.',
  'Good read but a bit slow in the middle sections.',
  'The characters are so well developed. One of my favorites.',
  'An engaging page-turner from start to finish.',
  'Not quite what I expected but still enjoyable.',
  'Beautifully written with a satisfying conclusion.',
  'A must-read for anyone interested in this genre.',
  'The plot twists kept me guessing until the very end.',
  'Solid writing and an interesting premise.',
  'One of the best books I have read this year.',
  'Thought-provoking and deeply moving.',
  'A bit predictable but well-crafted nonetheless.',
  'The author has a unique voice that draws you in.',
  'Perfect blend of humor and drama.',
];

function generateReviews(bookId: string, count: number): Review[] {
  const reviews: Review[] = [];
  for (let i = 0; i < count; i++) {
    reviews.push({
      id: `${bookId}-review-${i}`,
      userName: reviewerNames[i % reviewerNames.length],
      rating: Math.min(5, Math.max(3, 3 + Math.floor(Math.random() * 3))),
      comment: reviewComments[i % reviewComments.length],
      date: `2024-${String(Math.floor(Math.random() * 12) + 1).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
      helpful: Math.floor(Math.random() * 50),
    });
  }
  return reviews;
}


export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different?',
    price: 14.99,
    originalPrice: 18.99,
    imageUrl: 'https://picsum.photos/seed/book1/400/600',
    rating: 4.5,
    ratingCount: 2340,
    reviews: generateReviews('1', 5),
    genre: 'Fiction',
    isbn: '978-0-525-55947-4',
    pages: 288,
    publishDate: '2020-08-13',
    publisher: 'Viking Press',
    inStock: true,
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving — every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    price: 16.99,
    originalPrice: 22.00,
    imageUrl: 'https://picsum.photos/seed/book2/400/600',
    rating: 4.8,
    ratingCount: 8920,
    reviews: generateReviews('2', 5),
    genre: 'Self-Help',
    isbn: '978-0-7352-1129-2',
    pages: 320,
    publishDate: '2018-10-16',
    publisher: 'Avery',
    inStock: true,
  },
  {
    id: '3',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission — and if he fails, humanity and the earth itself will perish. Except that right now, he does not even know that. He is so far away that reaching Earth feels impossible.',
    price: 18.99,
    originalPrice: 24.99,
    imageUrl: 'https://picsum.photos/seed/book3/400/600',
    rating: 4.7,
    ratingCount: 5100,
    reviews: generateReviews('3', 5),
    genre: 'Science Fiction',
    isbn: '978-0-593-13520-4',
    pages: 496,
    publishDate: '2021-05-04',
    publisher: 'Ballantine Books',
    inStock: true,
  },
  {
    id: '4',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: 'Alicia Berenson\'s life is seemingly perfect. Until one evening her husband Gabriel returns home late and she shoots him five times in the face. Then never speaks another word. The mystery of why she pulled the trigger grips the nation.',
    price: 13.99,
    originalPrice: 17.99,
    imageUrl: 'https://picsum.photos/seed/book4/400/600',
    rating: 4.3,
    ratingCount: 4200,
    reviews: generateReviews('4', 5),
    genre: 'Mystery',
    isbn: '978-1-250-30169-7',
    pages: 325,
    publishDate: '2019-02-05',
    publisher: 'Celadon Books',
    inStock: true,
  },
  {
    id: '5',
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is a spice that extends life and expands consciousness.',
    price: 12.99,
    originalPrice: 16.99,
    imageUrl: 'https://picsum.photos/seed/book5/400/600',
    rating: 4.6,
    ratingCount: 12000,
    reviews: generateReviews('5', 5),
    genre: 'Science Fiction',
    isbn: '978-0-441-17271-9',
    pages: 688,
    publishDate: '1965-08-01',
    publisher: 'Ace Books',
    inStock: true,
  },
  {
    id: '6',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    description: 'For years, rumors of the marsh girl have haunted Barkley Cove. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say.',
    price: 14.49,
    originalPrice: 18.00,
    imageUrl: 'https://picsum.photos/seed/book6/400/600',
    rating: 4.5,
    ratingCount: 7800,
    reviews: generateReviews('6', 5),
    genre: 'Fiction',
    isbn: '978-0-7352-1909-0',
    pages: 384,
    publishDate: '2018-08-14',
    publisher: 'G.P. Putnam\'s Sons',
    inStock: true,
  },
  {
    id: '7',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Doing well with money is not necessarily about what you know. It is about how you behave. And behavior is hard to teach, even to really smart people. In this book, Morgan Housel shares 19 short stories exploring the strange ways people think about money.',
    price: 15.99,
    originalPrice: 19.99,
    imageUrl: 'https://picsum.photos/seed/book7/400/600',
    rating: 4.7,
    ratingCount: 6500,
    reviews: generateReviews('7', 5),
    genre: 'Non-Fiction',
    isbn: '978-0-85719-768-0',
    pages: 256,
    publishDate: '2020-09-08',
    publisher: 'Harriman House',
    inStock: true,
  },
  {
    id: '8',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    description: 'Told in Kvothe\'s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. A high-action story written with a survey beauty that is reminiscent of fantasy epics.',
    price: 11.99,
    originalPrice: 15.99,
    imageUrl: 'https://picsum.photos/seed/book8/400/600',
    rating: 4.6,
    ratingCount: 9800,
    reviews: generateReviews('8', 5),
    genre: 'Fantasy',
    isbn: '978-0-7564-0407-9',
    pages: 662,
    publishDate: '2007-03-27',
    publisher: 'DAW Books',
    inStock: true,
  },
  {
    id: '9',
    title: 'Becoming',
    author: 'Michelle Obama',
    description: 'In a life filled with meaning and accomplishment, Michelle Obama has emerged as one of the most iconic and compelling women of our era. As First Lady of the United States, she helped create the most welcoming White House in history.',
    price: 19.99,
    originalPrice: 28.00,
    imageUrl: 'https://picsum.photos/seed/book9/400/600',
    rating: 4.8,
    ratingCount: 11200,
    reviews: generateReviews('9', 5),
    genre: 'Biography',
    isbn: '978-1-5247-6313-8',
    pages: 448,
    publishDate: '2018-11-13',
    publisher: 'Crown Publishing',
    inStock: true,
  },
  {
    id: '10',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    description: 'Even bad code can function. But if code is not clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. Clean Code is a revolutionary paradigm in craftsmanship.',
    price: 34.99,
    originalPrice: 44.99,
    imageUrl: 'https://picsum.photos/seed/book10/400/600',
    rating: 4.4,
    ratingCount: 3200,
    reviews: generateReviews('10', 5),
    genre: 'Technology',
    isbn: '978-0-13-235088-4',
    pages: 464,
    publishDate: '2008-08-01',
    publisher: 'Prentice Hall',
    inStock: true,
  },
  {
    id: '11',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'The Great Gatsby captures the spirit of the Roaring Twenties. Through the eyes of narrator Nick Carraway, the novel explores themes of wealth, class, idealism, and the American Dream as embodied by the mysterious Jay Gatsby.',
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/book11/400/600',
    rating: 4.2,
    ratingCount: 15000,
    reviews: generateReviews('11', 5),
    genre: 'Fiction',
    isbn: '978-0-7432-7356-5',
    pages: 180,
    publishDate: '1925-04-10',
    publisher: 'Scribner',
    inStock: true,
  },
  {
    id: '12',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: 'From a renowned historian comes a groundbreaking narrative of humanity\'s creation and evolution that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be human.',
    price: 17.99,
    originalPrice: 24.99,
    imageUrl: 'https://picsum.photos/seed/book12/400/600',
    rating: 4.6,
    ratingCount: 8900,
    reviews: generateReviews('12', 5),
    genre: 'History',
    isbn: '978-0-06-231609-7',
    pages: 498,
    publishDate: '2015-02-10',
    publisher: 'Harper Perennial',
    inStock: true,
  },
  {
    id: '13',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'Bilbo Baggins is a hobbit who enjoys a comfortable life, rarely traveling far from his cozy home. His world is turned upside down when Gandalf the wizard and thirteen dwarves arrive to enlist him as a burglar on a quest for treasure.',
    price: 10.99,
    originalPrice: 14.99,
    imageUrl: 'https://picsum.photos/seed/book13/400/600',
    rating: 4.7,
    ratingCount: 18000,
    reviews: generateReviews('13', 5),
    genre: 'Fantasy',
    isbn: '978-0-547-92822-7',
    pages: 310,
    publishDate: '1937-09-21',
    publisher: 'Houghton Mifflin',
    inStock: true,
  },
  {
    id: '14',
    title: 'Educated',
    author: 'Tara Westover',
    description: 'Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her struggle for self-invention and quest for knowledge is a testament to the transformative power of education.',
    price: 14.99,
    originalPrice: 18.99,
    imageUrl: 'https://picsum.photos/seed/book14/400/600',
    rating: 4.5,
    ratingCount: 6700,
    reviews: generateReviews('14', 5),
    genre: 'Biography',
    isbn: '978-0-399-59050-4',
    pages: 352,
    publishDate: '2018-02-20',
    publisher: 'Random House',
    inStock: true,
  },
  {
    id: '15',
    title: 'The Girl on the Train',
    author: 'Paula Hawkins',
    description: 'Rachel takes the same commuter train every morning and evening. Every day she rattles down the track and stops at a signal that allows her to watch a couple as they eat breakfast on their deck. Until she sees something shocking.',
    price: 12.49,
    originalPrice: 16.00,
    imageUrl: 'https://picsum.photos/seed/book15/400/600',
    rating: 4.1,
    ratingCount: 5400,
    reviews: generateReviews('15', 5),
    genre: 'Mystery',
    isbn: '978-1-59463-266-8',
    pages: 323,
    publishDate: '2015-01-13',
    publisher: 'Riverhead Books',
    inStock: true,
  },
  {
    id: '16',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    description: 'This motivational personal development and self-help book was inspired by a suggestion from business magnate Andrew Carnegie. It remains the most important financial book ever written, summarizing the thirteen steps to riches.',
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/book16/400/600',
    rating: 4.3,
    ratingCount: 14500,
    reviews: generateReviews('16', 5),
    genre: 'Self-Help',
    isbn: '978-1-58542-433-7',
    pages: 233,
    publishDate: '1937-03-01',
    publisher: 'TarcherPerigee',
    inStock: true,
  },
  {
    id: '17',
    title: 'The Martian',
    author: 'Andy Weir',
    description: 'Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he is sure he will be the first person to die there. Stranded and alone, he must figure out how to survive on a hostile planet.',
    price: 13.99,
    originalPrice: 17.00,
    imageUrl: 'https://picsum.photos/seed/book17/400/600',
    rating: 4.6,
    ratingCount: 7200,
    reviews: generateReviews('17', 5),
    genre: 'Science Fiction',
    isbn: '978-0-553-41802-6',
    pages: 384,
    publishDate: '2014-02-11',
    publisher: 'Broadway Books',
    inStock: true,
  },
  {
    id: '18',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet and Fitzwilliam Darcy as they navigate societal expectations, family drama, and their own personal flaws on the path to unexpected love.',
    price: 7.99,
    imageUrl: 'https://picsum.photos/seed/book18/400/600',
    rating: 4.7,
    ratingCount: 22000,
    reviews: generateReviews('18', 5),
    genre: 'Romance',
    isbn: '978-0-14-143951-8',
    pages: 432,
    publishDate: '1813-01-28',
    publisher: 'Penguin Classics',
    inStock: true,
  },
  {
    id: '19',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    description: 'Based on more than forty interviews with Steve Jobs conducted over two years as well as interviews with family members, friends, adversaries, and colleagues, Walter Isaacson wrote a riveting story of his roller-coaster life.',
    price: 16.99,
    originalPrice: 22.50,
    imageUrl: 'https://picsum.photos/seed/book19/400/600',
    rating: 4.4,
    ratingCount: 5600,
    reviews: generateReviews('19', 5),
    genre: 'Biography',
    isbn: '978-1-4516-4853-9',
    pages: 656,
    publishDate: '2011-10-24',
    publisher: 'Simon & Schuster',
    inStock: true,
  },
  {
    id: '20',
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    description: 'The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process — taking a requirement and producing working, maintainable code that delights users.',
    price: 39.99,
    originalPrice: 49.99,
    imageUrl: 'https://picsum.photos/seed/book20/400/600',
    rating: 4.6,
    ratingCount: 2800,
    reviews: generateReviews('20', 5),
    genre: 'Technology',
    isbn: '978-0-13-595705-9',
    pages: 352,
    publishDate: '2019-09-13',
    publisher: 'Addison-Wesley',
    inStock: true,
  },
  {
    id: '21',
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    description: 'On a warm summer morning in Missouri, Nick Dunne\'s fifth wedding anniversary, his wife Amy suddenly disappears. Under mounting pressure from the police and growing media frenzy, Nick\'s portrait of a blissful union begins to crumble.',
    price: 13.49,
    originalPrice: 17.00,
    imageUrl: 'https://picsum.photos/seed/book21/400/600',
    rating: 4.2,
    ratingCount: 6300,
    reviews: generateReviews('21', 5),
    genre: 'Mystery',
    isbn: '978-0-307-58836-4',
    pages: 432,
    publishDate: '2012-06-05',
    publisher: 'Crown Publishing',
    inStock: true,
  },
  {
    id: '22',
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    description: 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast.',
    price: 14.99,
    originalPrice: 18.00,
    imageUrl: 'https://picsum.photos/seed/book22/400/600',
    rating: 4.5,
    ratingCount: 9100,
    reviews: generateReviews('22', 5),
    genre: 'Fantasy',
    isbn: '978-1-6196-3476-4',
    pages: 419,
    publishDate: '2015-05-05',
    publisher: 'Bloomsbury',
    inStock: true,
  },
  {
    id: '23',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'Paulo Coelho\'s masterwork tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different from what he originally envisioned.',
    price: 11.99,
    originalPrice: 15.00,
    imageUrl: 'https://picsum.photos/seed/book23/400/600',
    rating: 4.3,
    ratingCount: 16000,
    reviews: generateReviews('23', 5),
    genre: 'Fiction',
    isbn: '978-0-06-112241-5',
    pages: 197,
    publishDate: '1988-01-01',
    publisher: 'HarperOne',
    inStock: true,
  },
  {
    id: '24',
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    description: 'In Outliers, Malcolm Gladwell asks the question: what makes high-achievers different? He looks at everyone from rock stars to professional athletes, software billionaires to scientific geniuses, and reveals the hidden logic behind success.',
    price: 14.99,
    originalPrice: 18.99,
    imageUrl: 'https://picsum.photos/seed/book24/400/600',
    rating: 4.4,
    ratingCount: 7600,
    reviews: generateReviews('24', 5),
    genre: 'Non-Fiction',
    isbn: '978-0-316-01792-3',
    pages: 336,
    publishDate: '2008-11-18',
    publisher: 'Little, Brown',
    inStock: true,
  },
  {
    id: '25',
    title: 'It Ends with Us',
    author: 'Colleen Hoover',
    description: 'Lily hasn\'t always had it easy, but that\'s never stopped her from working hard for the life she wants. When Atlas, a former flame re-enters her life, everything she has built with Ryle is threatened.',
    price: 12.99,
    originalPrice: 16.99,
    imageUrl: 'https://picsum.photos/seed/book25/400/600',
    rating: 4.4,
    ratingCount: 10500,
    reviews: generateReviews('25', 5),
    genre: 'Romance',
    isbn: '978-1-5011-1038-8',
    pages: 384,
    publishDate: '2016-08-02',
    publisher: 'Atria Books',
    inStock: true,
  },
  {
    id: '26',
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    description: 'In this artful, informative, and delightful book, Jared Diamond convincingly argues that geographical and environmental factors shaped the modern world. Diamond puts the case that geography and biogeography molded the destiny of nations.',
    price: 15.99,
    originalPrice: 19.99,
    imageUrl: 'https://picsum.photos/seed/book26/400/600',
    rating: 4.3,
    ratingCount: 4800,
    reviews: generateReviews('26', 5),
    genre: 'History',
    isbn: '978-0-393-31755-8',
    pages: 528,
    publishDate: '1997-03-01',
    publisher: 'W. W. Norton',
    inStock: true,
  },
  {
    id: '27',
    title: 'Charlotte\'s Web',
    author: 'E.B. White',
    description: 'This beloved book follows the story of a pig named Wilbur and his friendship with a barn spider named Charlotte. When Wilbur is in danger of being slaughtered, Charlotte writes messages praising Wilbur in her web to save him.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/book27/400/600',
    rating: 4.8,
    ratingCount: 13000,
    reviews: generateReviews('27', 5),
    genre: 'Children',
    isbn: '978-0-06-093546-5',
    pages: 192,
    publishDate: '1952-10-15',
    publisher: 'Harper & Brothers',
    inStock: true,
  },
  {
    id: '28',
    title: 'Design Patterns',
    author: 'Gang of Four',
    description: 'Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and succinct solutions to commonly occurring design problems in a landmark book.',
    price: 42.99,
    originalPrice: 54.99,
    imageUrl: 'https://picsum.photos/seed/book28/400/600',
    rating: 4.3,
    ratingCount: 2100,
    reviews: generateReviews('28', 5),
    genre: 'Technology',
    isbn: '978-0-201-63361-0',
    pages: 395,
    publishDate: '1994-10-21',
    publisher: 'Addison-Wesley',
    inStock: true,
  },
  {
    id: '29',
    title: '1984',
    author: 'George Orwell',
    description: 'Among the seminal texts of the 20th century, 1984 is a rare work that grows more haunting as its prophecies are fulfilled. The novel follows Winston Smith, a low-ranking member of the Party in a totalitarian state.',
    price: 9.99,
    originalPrice: 13.99,
    imageUrl: 'https://picsum.photos/seed/book29/400/600',
    rating: 4.7,
    ratingCount: 25000,
    reviews: generateReviews('29', 5),
    genre: 'Fiction',
    isbn: '978-0-451-52493-5',
    pages: 328,
    publishDate: '1949-06-08',
    publisher: 'Signet Classics',
    inStock: true,
  },
  {
    id: '30',
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    description: 'One of the most inspiring and impactful books ever written. The 7 Habits have become famous and are integrated into everyday thinking by millions and millions of people. This book is a must-read for all.',
    price: 15.99,
    originalPrice: 21.00,
    imageUrl: 'https://picsum.photos/seed/book30/400/600',
    rating: 4.5,
    ratingCount: 9200,
    reviews: generateReviews('30', 5),
    genre: 'Self-Help',
    isbn: '978-1-4522-3964-2',
    pages: 381,
    publishDate: '1989-08-15',
    publisher: 'Free Press',
    inStock: true,
  },
  {
    id: '31',
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    description: 'While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of night. The elderly curator of the Louvre has been murdered. A baffling cipher is found near the body, launching a thrilling treasure hunt.',
    price: 12.99,
    originalPrice: 16.99,
    imageUrl: 'https://picsum.photos/seed/book31/400/600',
    rating: 4.1,
    ratingCount: 11000,
    reviews: generateReviews('31', 5),
    genre: 'Mystery',
    isbn: '978-0-307-47427-9',
    pages: 597,
    publishDate: '2003-03-18',
    publisher: 'Anchor Books',
    inStock: true,
  },
  {
    id: '32',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    description: 'Harry Potter has never been the star of a Quidditch team, or scored points in a magic spell. All he knows is a miserable life with the Dursleys. That is, until a mysterious letter arrives from Hogwarts.',
    price: 10.99,
    originalPrice: 14.99,
    imageUrl: 'https://picsum.photos/seed/book32/400/600',
    rating: 4.8,
    ratingCount: 35000,
    reviews: generateReviews('32', 5),
    genre: 'Fantasy',
    isbn: '978-0-590-35340-3',
    pages: 309,
    publishDate: '1997-06-26',
    publisher: 'Scholastic',
    inStock: true,
  },
  {
    id: '33',
    title: 'The Lean Startup',
    author: 'Eric Ries',
    description: 'Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
    price: 18.99,
    originalPrice: 24.00,
    imageUrl: 'https://picsum.photos/seed/book33/400/600',
    rating: 4.2,
    ratingCount: 4100,
    reviews: generateReviews('33', 5),
    genre: 'Non-Fiction',
    isbn: '978-0-307-88789-4',
    pages: 336,
    publishDate: '2011-09-13',
    publisher: 'Currency',
    inStock: true,
  },
  {
    id: '34',
    title: 'The Notebook',
    author: 'Nicholas Sparks',
    description: 'Set amid the austere beauty of the coastal Carolinas in 1946, The Notebook begins with the story of Noah Calhoun, a rural Southerner returned home from World War II. He is haunted by images of the beautiful girl he met fourteen years earlier.',
    price: 11.99,
    imageUrl: 'https://picsum.photos/seed/book34/400/600',
    rating: 4.3,
    ratingCount: 8900,
    reviews: generateReviews('34', 5),
    genre: 'Romance',
    isbn: '978-0-446-60573-5',
    pages: 214,
    publishDate: '1996-10-01',
    publisher: 'Grand Central Publishing',
    inStock: true,
  },
  {
    id: '35',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    description: 'A landmark volume in science writing by one of the great minds of our time, Stephen Hawking\'s book explores such profound questions as: How did the universe begin? And what made its start possible?',
    price: 14.99,
    originalPrice: 18.00,
    imageUrl: 'https://picsum.photos/seed/book35/400/600',
    rating: 4.5,
    ratingCount: 7100,
    reviews: generateReviews('35', 5),
    genre: 'Science Fiction',
    isbn: '978-0-553-38016-3',
    pages: 212,
    publishDate: '1988-04-01',
    publisher: 'Bantam',
    inStock: true,
  },
  {
    id: '36',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    description: 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. Harper Lee\'s Pulitzer Prize-winning masterwork of honor and injustice set in the Deep South.',
    price: 9.49,
    imageUrl: 'https://picsum.photos/seed/book36/400/600',
    rating: 4.8,
    ratingCount: 28000,
    reviews: generateReviews('36', 5),
    genre: 'Fiction',
    isbn: '978-0-06-093546-7',
    pages: 336,
    publishDate: '1960-07-11',
    publisher: 'Harper Perennial',
    inStock: true,
  },
  {
    id: '37',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    description: 'A guide to spiritual enlightenment. Eckhart Tolle takes readers on an inspiring spiritual journey to find their true and deepest self and reach the ultimate in personal growth and spirituality.',
    price: 13.99,
    originalPrice: 17.99,
    imageUrl: 'https://picsum.photos/seed/book37/400/600',
    rating: 4.4,
    ratingCount: 6800,
    reviews: generateReviews('37', 5),
    genre: 'Self-Help',
    isbn: '978-1-57731-480-6',
    pages: 236,
    publishDate: '1997-01-01',
    publisher: 'New World Library',
    inStock: true,
  },
  {
    id: '38',
    title: 'Mistborn: The Final Empire',
    author: 'Brandon Sanderson',
    description: 'In a world where ash falls from the sky and mist dominates the night, an evil being has gained control. Vin, a street urchin, discovers she possesses the powers of Allomancy — the mystical art of manipulating metals.',
    price: 12.99,
    originalPrice: 16.99,
    imageUrl: 'https://picsum.photos/seed/book38/400/600',
    rating: 4.6,
    ratingCount: 7800,
    reviews: generateReviews('38', 5),
    genre: 'Fantasy',
    isbn: '978-0-7653-1178-8',
    pages: 541,
    publishDate: '2006-07-17',
    publisher: 'Tor Books',
    inStock: true,
  },
  {
    id: '39',
    title: 'The Art of War',
    author: 'Sun Tzu',
    description: 'The Art of War is an ancient Chinese military treatise dating from the Late Spring and Autumn Period. The work is composed of 13 chapters, each devoted to a different set of skills related to warfare and strategy.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/book39/400/600',
    rating: 4.5,
    ratingCount: 12000,
    reviews: generateReviews('39', 5),
    genre: 'History',
    isbn: '978-1-59030-250-7',
    pages: 68,
    publishDate: '500-01-01',
    publisher: 'Shambhala',
    inStock: true,
  },
  {
    id: '40',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    description: 'Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness, covering a broad range of algorithms in depth.',
    price: 79.99,
    originalPrice: 99.99,
    imageUrl: 'https://picsum.photos/seed/book40/400/600',
    rating: 4.4,
    ratingCount: 1800,
    reviews: generateReviews('40', 5),
    genre: 'Technology',
    isbn: '978-0-262-03384-8',
    pages: 1312,
    publishDate: '2009-07-31',
    publisher: 'MIT Press',
    inStock: true,
  },
  {
    id: '41',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    description: 'The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through his own telling of events, Holden paints a revealing picture of himself and his world.',
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/book41/400/600',
    rating: 4.0,
    ratingCount: 15000,
    reviews: generateReviews('41', 5),
    genre: 'Fiction',
    isbn: '978-0-316-76948-0',
    pages: 234,
    publishDate: '1951-07-16',
    publisher: 'Little, Brown',
    inStock: true,
  },
  {
    id: '42',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    description: 'In the international bestseller, Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think — System 1 is fast and intuitive; System 2 is slow and deliberate.',
    price: 16.49,
    originalPrice: 20.00,
    imageUrl: 'https://picsum.photos/seed/book42/400/600',
    rating: 4.5,
    ratingCount: 7200,
    reviews: generateReviews('42', 5),
    genre: 'Non-Fiction',
    isbn: '978-0-374-53355-7',
    pages: 499,
    publishDate: '2011-10-25',
    publisher: 'Farrar, Straus and Giroux',
    inStock: true,
  },
  {
    id: '43',
    title: 'Me Before You',
    author: 'Jojo Moyes',
    description: 'Lou Clark knows lots of things — she knows her quirky fashion sense is unusual, she knows she likes working in The Buttered Bun tea shop. What she doesn\'t know is she\'s about to lose her job or that knowing what happens next would change her forever.',
    price: 11.49,
    originalPrice: 15.99,
    imageUrl: 'https://picsum.photos/seed/book43/400/600',
    rating: 4.3,
    ratingCount: 8100,
    reviews: generateReviews('43', 5),
    genre: 'Romance',
    isbn: '978-0-14-312444-1',
    pages: 369,
    publishDate: '2012-01-05',
    publisher: 'Penguin Books',
    inStock: true,
  },
  {
    id: '44',
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    description: 'In the ruins of a place once known as North America lies the nation of Panem, a Capitol surrounded by twelve outlying districts. Each year, the districts must provide one boy and one girl between twelve and eighteen for the annual Hunger Games.',
    price: 10.99,
    originalPrice: 14.99,
    imageUrl: 'https://picsum.photos/seed/book44/400/600',
    rating: 4.5,
    ratingCount: 18000,
    reviews: generateReviews('44', 5),
    genre: 'Science Fiction',
    isbn: '978-0-439-02348-1',
    pages: 374,
    publishDate: '2008-09-14',
    publisher: 'Scholastic',
    inStock: true,
  },
  {
    id: '45',
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    description: 'Max is sent to bed without his supper and imagines sailing away to the land of the Wild Things, where he becomes their king. A classic tale of childhood imagination and the comforts of home.',
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/book45/400/600',
    rating: 4.7,
    ratingCount: 9500,
    reviews: generateReviews('45', 5),
    genre: 'Children',
    isbn: '978-0-06-025492-6',
    pages: 48,
    publishDate: '1963-04-09',
    publisher: 'Harper & Row',
    inStock: true,
  },
  {
    id: '46',
    title: 'Sherlock Holmes: Complete Collection',
    author: 'Arthur Conan Doyle',
    description: 'Follow the legendary detective Sherlock Holmes and his loyal companion Dr. Watson as they solve the most baffling cases in Victorian London. This collection includes all four novels and fifty-six short stories.',
    price: 14.99,
    imageUrl: 'https://picsum.photos/seed/book46/400/600',
    rating: 4.8,
    ratingCount: 14000,
    reviews: generateReviews('46', 5),
    genre: 'Mystery',
    isbn: '978-0-553-21241-6',
    pages: 1122,
    publishDate: '1892-10-14',
    publisher: 'Bantam Classics',
    inStock: true,
  },
  {
    id: '47',
    title: 'Deep Work',
    author: 'Cal Newport',
    description: 'In this book, author Cal Newport flips the narrative on impact in a connected age. Deep work is the ability to focus without distraction on a cognitively demanding task — a skill that is becoming increasingly rare and increasingly valuable.',
    price: 14.99,
    originalPrice: 18.99,
    imageUrl: 'https://picsum.photos/seed/book47/400/600',
    rating: 4.4,
    ratingCount: 3800,
    reviews: generateReviews('47', 5),
    genre: 'Self-Help',
    isbn: '978-1-4555-8669-1',
    pages: 296,
    publishDate: '2016-01-05',
    publisher: 'Grand Central Publishing',
    inStock: true,
  },
  {
    id: '48',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    description: 'One Ring to rule them all. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron forged the One Ring, filling it with his own power so that he could rule all others. Now the fate of civilization rests with a hobbit.',
    price: 22.99,
    originalPrice: 29.99,
    imageUrl: 'https://picsum.photos/seed/book48/400/600',
    rating: 4.9,
    ratingCount: 30000,
    reviews: generateReviews('48', 5),
    genre: 'Fantasy',
    isbn: '978-0-618-64015-7',
    pages: 1178,
    publishDate: '1954-07-29',
    publisher: 'Mariner Books',
    inStock: true,
  },
  {
    id: '49',
    title: 'The Emperor of All Maladies',
    author: 'Siddhartha Mukherjee',
    description: 'Winner of the Pulitzer Prize, The Emperor of All Maladies is a magnificent, profoundly humane biography of cancer — from its first documented appearances thousands of years ago through the epic battles in the twentieth century.',
    price: 16.99,
    originalPrice: 21.00,
    imageUrl: 'https://picsum.photos/seed/book49/400/600',
    rating: 4.6,
    ratingCount: 4200,
    reviews: generateReviews('49', 5),
    genre: 'History',
    isbn: '978-1-4391-0795-9',
    pages: 571,
    publishDate: '2010-11-16',
    publisher: 'Scribner',
    inStock: true,
  },
  {
    id: '50',
    title: 'You Don\'t Know JS',
    author: 'Kyle Simpson',
    description: 'No matter how much experience you have with JavaScript, odds are you still don\'t fully understand the language. This concise, in-depth guide takes you inside scope and closures, two core concepts you need to understand to become a more efficient programmer.',
    price: 24.99,
    originalPrice: 34.99,
    imageUrl: 'https://picsum.photos/seed/book50/400/600',
    rating: 4.5,
    ratingCount: 2600,
    reviews: generateReviews('50', 5),
    genre: 'Technology',
    isbn: '978-1-491-90415-4',
    pages: 98,
    publishDate: '2014-03-10',
    publisher: "O'Reilly Media",
    inStock: true,
  },
];


export const GENRE_COLORS: Record<string, string> = {
  'Fiction': '#E67E22',
  'Non-Fiction': '#3498DB',
  'Science Fiction': '#9B59B6',
  'Mystery': '#E74C3C',
  'Romance': '#E91E63',
  'Self-Help': '#27AE60',
  'Biography': '#F39C12',
  'Fantasy': '#8E44AD',
  'Technology': '#2196F3',
  'History': '#795548',
  'Children': '#FF9800',
  'All': '#607D8B',
};
